- cmd/main.go
- go.mod
This PR adds:
- go.mod file
- main.go file
> Add go project skeleton

- .gitignore
- Dockerfile
- Makefile
- hack/detect_cri.sh
This PR introduces the Dockerfile that will build the project.
pushed on top of #1
> Add Dockerfile to build project

- .dockerignore
- .github/workflows/main.yaml
This PR creates a new gitactions workflow which is required in order to kickstart the gitactions engine
> githubActions: Add a noop job

- Makefile
- hack/check-uncommitted.sh
- hack/go-mod-version.sh
Adding go infra tools that will assist the developers of these repo.
> Add go infra tools

- .github/workflows/main.yaml
- Makefile
This PR introduces CI checks that will run on each PR
> Add CI gitactions job

- tests/checkup_test.go
Add minor improvements to the e2e test based on PR https://github.com/kiagnose/kubevirt-rt-checkup/pull/19.
> e2e: Minor improvements

- pkg/internal/checkup/checkup.go
- pkg/internal/checkup/checkup_test.go
- pkg/internal/client/client.go
- tests/checkup_test.go
This PR adds the Traffic generator Pod part in the teardown method.
> Teardown: Traffic generator Pod

- pkg/internal/checkup/checkup_test.go
Remove NetworkAttachmentDefinition leftovers.
> checkup, test: Remove references to NetworkAttachmentDefinition

- pkg/internal/checkup/checkup_test.go
Currently, the clientStub did not save the VMI and Pod's namespace upon their creation.
Currently, the existence of the VMI / Pod is not checked before deleting the object.
Add a check if the VMI / Pod exists before deleting it, or return an error in case it doesn't exist.
This uncovered a problem that was caused by the fact the VMI / Pod namespace was not stored.
Store the VMI / Pod namespace upon their creation.
~~This PR depends on PR #29.~~
> checkup, tests: Check if VMI / Pod exists before deleting it

- Makefile
- pkg/internal/checkup/checkup.go
- pkg/internal/checkup/pod/pod_test.go
- pkg/internal/checkup/pod/spec.go
- pkg/internal/config/config.go
- pkg/internal/config/config_test.go
- tests/checkup_test.go
- tests/test_suite_test.go
This PR is adding a runtimeclassname parameter to the configmap params.
> config: Add runtimeclassname parameter

- Makefile
- pkg/internal/checkup/checkup.go
- traffic-gen/Dockerfile
- traffic-gen/scripts/main.sh
- traffic-gen/scripts/run_traffic_gen_daemon.sh
- traffic-gen/scripts/set_tests_files.sh
- traffic-gen/scripts/set_traffic_gen_cfg_file.sh
- traffic-gen/templates/testpmd.py.in
- traffic-gen/templates/testpmd_addr.py.in
- traffic-gen/templates/trex_cfg.yaml.in
Currently the checkup is using a preset container image that runs the trex application on the pod.
Introducing the container image, as well as the scripts that configure the trex application and run it.
The parameters for this application are set by the checkup's params during the pod's run.
The pushed trex image is set as a build arg during the checkup's docker build process so that it can use the updated image.
> Introduce Traffic Generator container

- pkg/internal/checkup/checkup.go
- pkg/internal/checkup/pod/pod_test.go
- pkg/internal/checkup/pod/spec.go
This PR is making changes in order to reduce the teardown process of the checkup.
> Reduce Teardown time

- pkg/internal/checkup/executor/executor.go
- pkg/internal/checkup/executor/trex-console.go
This PR implements the traffic test inside the executer module
> executer: Run traffic test

- pkg/internal/checkup/executor/executor.go
- pkg/internal/checkup/executor/trex-console.go
- pkg/internal/checkup/executor/trex_console_types.go
This PR implements the functions that parse the statistics recieved from the DPDK applicatin and trex application, in order to pass them to the results struct in a future PR
> executer, Parse test outputs

- tests/checkup_test.go
Currently the e2e test waits for a JobComplete status, so if the checkup job fails then the test hangs until the timeout.
Check for JobFailed condition and fail with an informative error fail.
> e2e: Fail faster if checkup has failed

- README.md
> README: Add Checkup Results Retrieval section

- pkg/mainflow.go
Not all params were updated in the printConfig() function. This PR is adding the missing params
> mainflow: Add missing param prints

- README.release.md
Add release instructions based on the ones kiagnose/kiagnose [1]
[1] https://github.com/kiagnose/kiagnose/blob/6e3194ad309ab0fab8476da74023e5f7eb0dc7ee/README.release.md
> Add release instructions

- CHANGELOG
Add the CHANGELOG file to record release notes.
> Add CHANGELOG

- README.release.md
Added missing container images:
- kubevirt-dpdk-checkup-traffic-gen
- kubevirt-dpdk-checkup-vm
> README.release.md: Update container images section

- docs/Configuring_openshift_virtualization_vm_for_dpdk.md
This article is directly talking about D/S products, so it may move to
another location in the future.
> docs: Add article on configuring DPDK on VM

- README.md
- pkg/internal/checkup/checkup.go
- pkg/internal/checkup/pod/spec.go
- tests/checkup_test.go
This is a cherry-pick of PR #102.
> [Release 0.1] Add a dedicated ServiceAccount for the traffic-gen Pod

- pkg/internal/client/client.go
Reorder the file, so it will consist of:
1. VMI methods
2. Pod methods
3. NetworkAttachmentDefinition method
4. Helper function
> Client: Move Pod-related methods

- Makefile
This PR is a cherry-pick of #115
> [traffic-gen-in-vm] makefile, test/e2e: parametize KUBECONFIG

- tests/checkup_test.go
> [traffic-gen-in-vm] E2E: Fix output fields assertions

- pkg/internal/checkup/executor/executor.go
- pkg/internal/checkup/executor/testpmd-console.go
- pkg/internal/checkup/executor/testpmd/console.go
This PR moves the testpmd functions to a separate package.
> Move testpmd package

- pkg/internal/checkup/executor/executor.go
- pkg/internal/checkup/trex/client.go
Currently, most of the TRex client's methods receive a vmiName parameter.
This client is supposed to work against a single VMI. 
Add a vmiName field to the trex.Client struct.
Remove vmiName parameter from the relevant Client methods.
> [traffic-gen-in-vm] TRex: Add traffic-gen VMI name field

- pkg/mainflow.go
This PR is printing the timeout to as part of the input param logging.
> Add timeout to log

- README.md
Following a review by a native speaker, update the output fields' description.
> README: Update output fields' description

- pkg/internal/checkup/trex/client.go
- pkg/internal/checkup/trex/configfiles.go
- pkg/internal/checkup/trex/configfiles_test.go
This PR does minor refactor changes on the consts used in this package.
> trex: Refactor consts

- pkg/internal/checkup/executor/testpmd/console_test.go
This PR is adding unit tests to check the testpmd stats parsing.
> Add testpmd Unit tests

- pkg/internal/checkup/trex/client_test.go
- pkg/internal/checkup/trex/types.go
This PR is adding unit tests to check the trex stats parsing.
> Add trex Unit tests

- pkg/internal/checkup/checkup.go
Currently, the setup is using the global context, which has the timeout set by the user.
In case the checkup had created in VMIs, there is a wait for both VMIs to be ready, that does not fail until the global timeout.
If the user-supplied timeout is long, the checkup will wait for a long time before failing.
Add a context with a ten minutes timeout for the setup phase, derived from the global context.
Fixes [BZ 2243672](https://bugzilla.redhat.com/show_bug.cgi?id=2243672).
> Checkup, setup: Add setup context

- pkg/internal/checkup/executor/testpmd/console.go
- pkg/internal/checkup/executor/testpmd/console_test.go
Currently the command used to configure the testpmd is not configured properly.
This PR introduces the changes needed, using the testpmd API [0] and a reference repo [1].
[0] https://doc.dpdk.org/guides-16.04/testpmd_app_ug/run_app.html
[1] https://github.com/perftool-incubator/bench-trafficgen
> testpmd: Refactor App configuration

- CHANGELOG
In preparation for the release of v0.3.1 which contains the bug fix for the login race issue.
~~Depends on #226, please review only the last commit.~~
> [release-0.3] Update CHANGELOG

- Makefile
Bump the base image tag to the latest stable.
> Makefile: Bump checkup base image
