kiagnose/kubevirt-dpdk-checkup

.github/workflows/publish.yaml

Add the publish workflow, in order to push the
checkup's image to `quay.io/kiagnose/kubevirt-dpdk-checkup:<tag>`.

github actions: Add publish workflow

---

Makefile

This PR fixes the push makefile target, after currently it is [failing](https://github.com/kiagnose/kubevirt-dpdk-checkup/actions/runs/3874387752).

Fix push makefile target 

---

.golangci.yml
Makefile

This PR adds a config file that configures `make lint` to use the linters needed for this project

golangci-lint: Add config file

---

tests/checkup_test.go

Currently, the linter is complaining that a line is too long. Break that function call to multiple lines.

tests: Fix linter problem

---

.dockerignore
.gitignore
Makefile

Currently, it takes several minutes for the lint, unit-test and build targets to complete locally.
Add a cache directory for the lint target, and another one for the unit-test and build targets.
The addition of cache speeds up the build process.

Makefile: Add cache to build, unit-test and lint targets

---

Makefile

The backtick form of command substitution is deprecated in favor of: $(cmd).
Replace the usages of `pwd` with $(CURDIR).

Makefile: Replace deprecated form of command substitution

---

pkg/internal/checkup/checkup.go
pkg/internal/checkup/checkup_test.go
pkg/internal/launcher/launcher.go
pkg/internal/launcher/launcher_test.go
pkg/internal/reporter/reporter.go
pkg/internal/reporter/reporter_test.go
pkg/internal/status/status.go
pkg/mainflow.go
vendor/github.com/kiagnose/kiagnose/kiagnose/status/status.go
vendor/modules.txt

Introduce the project's skeleton, comprised of the following packages:
status
launcher
checkup
reporter
They are based on the VM latency checkup's packages with the same name[1].
[1] https://github.com/kiagnose/kiagnose/tree/95d8c7995fabbb7be11f7cde0eca57dc01e222bb/checkups/kubevirt-vm-latency/vmlatency/internal/
based on #15

Pkg Project skeleton

---

pkg/internal/config/config.go
pkg/internal/config/config_test.go
pkg/mainflow.go

According to trex [manual](https://trex-tgn.cisco.com/trex/doc/trex_manual.html#_creating_minimum_configuration_file), we need 2 NICs per trex pod and testpmd - this is to run inbound and outbound traffic on separate paths. 
This PR splits the MAC address param of both Traffic generator and DPDK to west and east params.

config: Add east west params

---

.dockerignore
.gitignore
Makefile

Currently, if the linter cache directory exists,
the `go mod tidy` command fails, because it doesn't have permissions to read it.
Add an underscore as a prefix to the `go-cache`
and `linter-cache` directories, so the `go mod tidy` command will ignore them[1].
Apply to `.gitignore` and `.dockerignore` as well.
[1] https://pkg.go.dev/cmd/go#hdr-Package_lists_and_patterns
Based on PR https://github.com/kiagnose/kubevirt-rt-checkup/pull/18.

Makefile: Make go tools ignore go and linter cache dirs

---

cmd/main.go
go.mod
pkg/internal/checkup/checkup.go
pkg/internal/checkup/checkup_test.go
pkg/internal/checkup/vmi/vmi.go
pkg/internal/client/client.go
pkg/mainflow.go
tests/checkup_test.go
vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
vendor/modules.txt

Create the VirtualMachineInstance object to be used as a test subject.
A follow-up PR will also wait for the VMI to boot.
The VMI object is created with a random suffix, in order to enable execution of multiple checkup instances simultaneously.
Manually tested against an OpenShift Virtualization 4.11 cluster.
Based on PR https://github.com/kiagnose/kubevirt-rt-checkup/pull/17

checkup, setup: Add VirtualMachineInstance creation

---

pkg/internal/checkup/checkup.go
pkg/internal/checkup/checkup_test.go
pkg/internal/client/client.go
tests/checkup_test.go

Delete the VirtualMachineInstance object and wait for its deletion during the teardown stage.
Manually tested against an OpenShift Virtualization 4.11 cluster.
~~Depends on PR #20.~~
Based on PR https://github.com/kiagnose/kubevirt-rt-checkup/pull/20.

checkup, teardown: Delete the VMI and wait for its deletion

---

pkg/internal/checkup/checkup.go
pkg/internal/checkup/vmi/vmi.go

Add OwnerReference to the VMI, so it would be automatically garbage collected, when the checkup's Pod would be deleted.
Manually tested against an OpenShift Virtualization 4.12 cluster. 

checkup, newDPDKVMI: Add OwnerReference to VMI

---

pkg/internal/checkup/checkup.go
pkg/internal/checkup/pod/container.go
pkg/internal/checkup/pod/pod_test.go
pkg/internal/checkup/pod/spec.go

TRex application needs access to the kernel modules to work properly.
Mounting libmodules to the traffic generator pod.

checkup, pod: Mount libmodules

---

pkg/internal/checkup/checkup.go
pkg/internal/checkup/checkup_test.go
tests/checkup_test.go

Wait for the VMI to boot by waiting for its `VirtualMachineInstanceAgentConnected` condition to be true, or timeout.
~~This PR depends on PR #30.~~

checkup, setup: Wait for VMI to boot

---

pkg/mainflow.go

Currently, the int values are not logged correctly.
Add a conversion to fix it.

mainflow, printConfig(): Log int values as string

---

pkg/internal/checkup/checkup.go
pkg/internal/checkup/checkup_test.go

Trex is an implementation detail, hide it for external usage.

checkup: Rename Trex to TrafficGenerator

---

pkg/internal/checkup/checkup.go
pkg/internal/checkup/pod/container.go
pkg/internal/checkup/pod/pod_test.go

Container disk image is a KubeVirt term, not applicable to regular containers.

checkup, container: Rename ContainerDiskImage to ContainerImage

---

pkg/internal/checkup/checkup.go
pkg/internal/checkup/checkup_test.go

Currently, the cloud-init data is hard-coded.
Generate the cloud-init using a function, in order to be able to share the credentials with the component that will log in to the VMI in a follow-up commit.

checkup: Generate cloud-init data

---

pkg/internal/checkup/checkup.go
pkg/internal/checkup/console/console.go
pkg/internal/checkup/executor/executor.go
pkg/internal/config/config.go
pkg/mainflow.go

1. Build the testpmd command line arguments.
2. Wait for it to successfully initialize.
3. Start it.

executor: Run testpmd

---

pkg/internal/checkup/checkup.go

Minor refactoring of the `checkup.go` file:
1. Put all Pod's non-exported methods under the VMI's non-exported methods.
2. Put all exported helper functions after them.
3. Put all non-exported helper functions after them.
Add a log entry when creating a VMI.

checkup: Minor refactor

---

tests/checkup_test.go

Adding minor changes:
- Fix the condition to fail earlier if Job is not found.
- Adding check of the Success field in the configmap.Data
- Adding prettify format of the Data for better readability in case of test failure
- Reducing test duration to 1 minute.

e2e: Add minor changes to the test

---

pkg/internal/checkup/checkup.go
pkg/internal/checkup/executor/executor.go
pkg/internal/reporter/reporter.go
pkg/internal/reporter/reporter_test.go
pkg/internal/status/status.go

This PR add the results collected from the executer module to the results struct, making the checkup operational.
pushed on top of #48

checkup, results: Update test params

---

pkg/internal/checkup/executor/executor.go

Currently, two methods are using a local const named "testpmdPromt", with the same value.
Increase its scope, and use it from both methods.
Also fix the typo.

checkup, executor: Use a single const for testpmdPrompt

---

pkg/internal/checkup/executor/trex-console.go

This PR does a small refactoring of the way we get the context in the `MonitorDropRates` function.

executer, trex-console: Change context usage

---

.gitignore
Makefile
vm/Dockerfile
vm/image-builder/Dockerfile
vm/scripts/build-vm-image
vm/scripts/customize-vm
vm/scripts/first-boot

Currently, the checkup uses a hard-codded name of a PVC containing a custom image.
In order for the checkup to be usable for other users, build a container disk [1] image.
Process description:
1. Bulid the vm-image-builder container image - this will be the environment to build the custom qcow2 image.
2. Build the custom qcow2 image using `virt-builder` [2].
3. Containerize the qcow2 image, so it could be consumed by KubeVirt.
4. Push the container disk image to `quay.io/kiagnose/kubevirt-dpdk-checkup-vm`.
```bash
make build-vm-container-disk
make push-vm-container-disk
```
A follow-up PR will add the URL of this image to the checkup's configuration.
[1] https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#containerdisk
[2] https://libguestfs.org/virt-builder.1.html

Build custom VM container disk image

---

pkg/internal/checkup/executor/trex-console.go

Currently the duration is set in minutes, making it so that the granularity of the test duration is minutes.
This is changed to allow seconds granularity [0]
[0] https://trex-tgn.cisco.com/trex/doc/trex_console.html, section 1.3.3.

executer, trex-console: Fix duration format

---

pkg/internal/checkup/checkup.go
pkg/internal/reporter/reporter.go
pkg/internal/reporter/reporter_test.go
tests/checkup_test.go

This PR fixed a bug where the results configmap did not register the vmi node name.
The vmi is saved after the vmi is booted, thus making sure the node name is set on it.
Also fixing a typo in the node name key

checkup: Get last updated vmi after waiting to be booted

---

Makefile

Currently, the `build-traffic-gen` and `push-traffic-gen` targets are in the middle of checkup-related targets.
Move them after the checkup-related targets, before the vm-related targets.

Makefile: Move build-traffic-gen and push-traffic-gen

---

README.md
pkg/internal/checkup/checkup.go
pkg/internal/checkup/checkup_test.go
pkg/internal/config/config.go
pkg/internal/config/config_test.go
pkg/mainflow.go
tests/checkup_test.go
traffic-gen/scripts/set_traffic_gen_cfg_file.sh

This PR is removing the NUMASocket param from the configmap, in favor of a dynamic set of it inside the traffic-gen pod

Remove NUMA socket param

---

Makefile

Currently, the traffic-gen container image is pushed twice with the same tag (latest).
Push the image with the git hash tag.

Makefile, push-traffic-gen: Push git tag

---

.github/workflows/main.yaml
.github/workflows/publish.yaml

In preparation for the first release, tag the checkup and traffic generator images with the release name, for example: `v0.1.0`.
The Latest image tag will be `main`.
Also add a trigger to the CI on release branches.

github actions: Preparation for first release

---

.github/workflows/vm_containerdisk.yaml
.github/workflows/vm_containerdisk_publish.yaml

Currently, the build and push of ContainerDisk image is performed manually.
Add a workflow to build the ContainerDisk image on PRs that changes the `vm` directory or one of its children.
Add a workflow to build and push the ContainerDisk image to quay when a PR gets merged, or when there is a new tagged version.

github actions: Build and publish VM ContainerDiskImage

---

README.md
pkg/internal/config/config.go
pkg/internal/config/config_test.go
tests/test_suite_test.go

Currently running the checkup with only mandatory parameters is broken, following the change done in #65 , where the default image tags were changed to `main`. 
In order to be able to run the checkup with only mandatory image params, aligning the default values of the dpdk-checkup, traffic-generator and DPDK vmi

Update checkups image tags to `main`

---

README.md

This PR removes an optional param `trafficGeneratorImage` from configmap example.
As this param is optional, it has a default value, if it is not set.

README: Remove optional param from configmap example

---

pkg/internal/checkup/vmi/vmi.go

Following PR #65 [1], the latest image tag is "main". This now causes KubeVirt to use the "IfNotPresent" ImagePullPolicy [2], where before it was implicitly "PullAlways".
Explicitly use the "PullAlways" policy.
[1] https://github.com/kiagnose/kubevirt-dpdk-checkup/pull/65
[2] http://kubevirt.io/api-reference/v0.58.1/definitions.html#_v1_containerdisksource

checkup, vmi: Always pull VM ContainerDisk image

---

pkg/internal/checkup/executor/executor.go

Currently the testpmd is forwarding on all CPUs given to it. In order to make sure that the packets are received and forwarded only on CPUs set as isolated by linux /proc/cmdline (set [here](https://github.com/kiagnose/kubevirt-dpdk-checkup/blob/6685c0060021275c115a1f58c661e253f5ca9dec/vm/scripts/customize-vm#L23)), changing the CPUs on the dpdk-testpmd command accordingly.
Also setting nb-cores according to [dpdk manual](https://doc.dpdk.org/guides/testpmd_app_ug/run_app.html).

execute, testpmd: Use only isolated CPUs

---

docs/rhel_dpdk_container_disk_image.md

Currently, the VM ContainerDisk image is based on CentOS stream 8.
Add instructions to build the ContainerDisk image based on RHEL 8.7.

docs: Add instructions to build RHEL 8.7 DPDK ContainerDisk

---

pkg/internal/checkup/checkup.go

This PR is merging the two separate failure result of the dpdk VM into one failure result.

checkup, testpmd: Join Tx and Rx errors

---

README.md
pkg/internal/checkup/checkup.go
pkg/internal/checkup/executor/executor.go
pkg/internal/reporter/reporter.go
pkg/internal/reporter/reporter_test.go
pkg/internal/status/status.go

This PR introduces a new criteria for failing the checkup. 
The checkup should fail if there were any ierrors present during the test.
This PR is pushed on top of #75

checkup, traffic-gen: Add ierrors result

---

pkg/internal/checkup/executor/executor.go

Currently, the tespmd forwards statistics are only partially parsed by extracting the accumulated/summary stats of the forwarded statistics output.
Introducing a more wholesome approach that parses both port stats and the accumulated stats and returns an array of all the statistics returned by the forward statistics testpmd command.

executer, testpmd: Enhance testpmd parsing

---

traffic-gen/Dockerfile

This PR is upgrading the trex application to v3.02.

traffic-gen: Upgrade trex to v3.02

---

pkg/internal/checkup/executor/executor.go
traffic-gen/templates/testpmd.py.in
traffic-gen/templates/testpmd_addr.py.in

currently the direction the traffic generator is sending the packets is from port 0 using the west src MAC, but since the DPDK application is configured to receive the east MAC on port 0, then the ports gets mixed. 
This does not effect the nature of the checkup, but for the sake of order, the checkup traffic diagram should be like this: 
```
traffic-gen[port 0] => dpdk-app[port 0] => dpdk-app[port 1] traffic-gen[port 1].
```
Switching the MACs on the traffic generator streams templates.

traffic-gen: Align ports with DPDK VMI

---

traffic-gen/scripts/run_traffic_gen_daemon.sh

This PR is removing the scapy server from running inside the traffic-generator pod.
The server is causing the application to crash on some machines. Since it is not necessary for the checkup, removing the scapy server by adding the flag.

traffic-gen: Add no-scapy-server flag

---

docs/Configuring_openshift_virtualization_vm_for_dpdk.md

This PR is fixing a typo in the document stating how to configure a VMI for DPDK workloads.
the parameter value used in the json annotation is wrong, and the use of spaces is causing the command to fail on simple copy.

docs: Fix HCO json annotation

---

traffic-gen/scripts/run_traffic_gen_daemon.sh

This PR is a semi-auto cherry-pick of https://github.com/kiagnose/kubevirt-dpdk-checkup/pull/98
Fixes [BZ#2178629](https://bugzilla.redhat.com/show_bug.cgi?id=2178629)

[release 0.1] traffic-gen: Add no-scapy-server flag

---

README.md

Following PRs #65 and #68, the VM containerDisk image and traffic-gen image are tagged as `main` for the main branch or `vx.y.z` for a release.
Fix the image URLs in the README accordingly.

README: Update image URLs of VM and traffic-gen

---

README.md

Following PR #63, the latest checkup's image tag is `main`. Update the Job's image tag in the README accordingly.

README: Change Job image to "main"

---

docs/Configuring_openshift_virtualization_vm_for_dpdk.md

Following a [PR](https://github.com/kubevirt/hyperconverged-cluster-operator/pull/2370) on HCO, this PR is updating our current documentation accordingly with the proper way to update the `defaultRuntimeClass` field.

docs: Update defaultRuntimeClass API

---

pkg/internal/checkup/checkup.go

In order to debug SCC related problems, print the traffic generator pod's manifest, if the user had specified `verbose` to be `true`.
Manually tested against an OpenShift Virtualization 4.13 cluster.

checkup: Add debug log of the traffic-gen pod's manifest

---

pkg/internal/checkup/checkup.go
pkg/internal/checkup/checkup_test.go

Currently, teardown does not happen in case a setup failure occurs.
The VMI and pod are owned by the checkup, so k8s will garbage collect them when the checkup will be deleted [1].
Add explicit cleanup of the VMI and the pod.
Based on kiagnose PR kiagnose/kiagnose#239
[1] https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/

checkup, setup: Cleanup VMI and Pod in case of error

---

.github/workflows/main.yaml
.github/workflows/publish.yaml
Makefile

Currently, the checkup image `build` and `push` targets are dependent on the traffic generator image matching targets.
This dependency disables the ability to build or push only the checkup image.
Make the `build` and `push` targets of the checkup image independent of the traffic generator image targets.

Makefile: Make checkup and traffic-gen independent

---

pkg/internal/checkup/checkup.go
pkg/internal/checkup/vmi/vmi.go
vm/scripts/customize-vm

The current checkup request 8 hugepages of size 1Gi on each end of the checkup (the traffic generator pod and the DPDK checkup VMI).
This request is unnecessarily big and means we can't run the checkup on smaller clusters.
Reducing the amount to 1 Hugepages on the traffic generator side
Reducing the amount to 4 Hugepages DPDK VMI side (which currently gives off only 1 allocated).

checkup: Reduce Hugepage demand in checkup objects

---

pkg/internal/checkup/executor/executor.go
pkg/internal/checkup/trex/client.go

Currently, the `executor` package depends on the `trex.PodExecuteClient` interface.
This makes a high-level package depend on the implementation of a lower-level package [1].
Add `podExecuteClient` interface to the `executor` package.
Unexport `trex.PodExecuteClient`.
Tested against an OpenShift Virtualization 4.14 cluster.
[1] https://en.wikipedia.org/wiki/Dependency_inversion_principle

Executor: Add podExecuteClient interface

---

tests/checkup_test.go

Currently, the assertions that the following fields are not empty, are broken:
1. `status.result.trafficGeneratorNode`
2. `status.result.DPDKVMNode`
We haven't seen the above assertions failure,
because the checkup constantly fails due to OCP bugs.

E2E: Fix output fields assertions

---

Makefile

In order to allow flexibility in the location of the kubeconfig file, updating the test/e2e target on the makeFile.

makeFile, test/e2e: parametize KUBECONFIG

---

.github/workflows/main.yaml
.github/workflows/publish.yaml
.github/workflows/vm_containerdisk.yaml
.github/workflows/vm_containerdisk_publish.yaml

Currently, the CI is running when creating a PR or pushing to the `main` or release branches.
In order to enable work on the development branch, enable the CI flow on it.

[traffic-gen-in-vm] Enable CI on traffic-gen-in-vm branch

---

go.mod
pkg/internal/checkup/checkup_test.go

Following PR #119, the traffic generator pod was removed.
Remove the leftover Pod and NAD operation from the client stub.

Checkup, tests: Remove Pod and NAD from client stub

---

pkg/internal/checkup/checkup.go
pkg/internal/checkup/checkup_test.go
pkg/internal/checkup/executor/executor.go

Currently, the checkup creates a single VMI object that represents the VMI under test.
Refactor the `checkup` package so it would be easier for follow-up PRs to add the traffic generator VMI.
Tested against an OpenShift Virtualization 4.14 cluster.

[traffic-gen-in-vm] Refactor the checkup package

---

vms/vm-under-test/scripts/first-boot

Currently, the VM under test has two SR-IOV NICs configured with static pre-defined PCI addresses.
The above PCI addresses are set in advanced when the containerDisk image is built.
The checkup assumes that these PCI addresses has a certain pre-defined value when it configures and executes `testpmd`.
In PR #126 there was a request [1] to change the PCI addresses of the SR-IOV NICs in the traffic generator image.
It was mistakenly changed in the image of the VM under test [2].
The above change caused problems with `testpmd` which in turn caused the E2E test to fail.
Restore the previous PCI addresses.
[1] https://github.com/kiagnose/kubevirt-dpdk-checkup/pull/126#discussion_r1259628429
[2] https://github.com/kiagnose/kubevirt-dpdk-checkup/compare/3475a2212740c591f9865c71aac2a3c09bd53c2c..2d …

[traffic-gen-in-vm] VM under test, image: Fix wrong PCI addresses

---

pkg/internal/checkup/checkup.go
pkg/internal/checkup/checkup_test.go
pkg/internal/checkup/vmi/vmi.go
pkg/internal/checkup/vmi/vmi_test.go

Currently, the logic that builds the VMI-under-test's spec is located at `checkup.go`.
The above logic is in a lower level of abstraction than checkup.
Move the low-level logic to the `vmi` package, while keeping the high-level logic at checkup.
This will allow a follow-up PR to easily add the traffic generator VMI.
A follow-up PR could also un-export the internal entities of the `vmi` package.

[traffic-gen-in-vm] Checkup: Move low-level VMI building logic to vmi package

---

pkg/internal/checkup/checkup.go
pkg/internal/checkup/vmi/affinity.go
pkg/internal/checkup/vmi/affinity_test.go

Currently, the affinity calculation logic of the VMI under test, is located
under `checkup.go`.
This logic is going to be shared between the VMI under test and the
traffic generator.
Move the affinity calculation logic to a shared location.
Also add unit tests.

[traffic-gen-in-vm] Move affinity calculation to vmi package

---

pkg/internal/checkup/checkup.go
pkg/internal/checkup/checkup_test.go
tests/checkup_test.go

Add the traffic generator VMI:
Setup:
1. Create it.
2. Wait for it to boot.
Run:
Report the node name on which it was scheduled.
Teardown:
1. Delete it.
2. Wait for it to be deleted.

[traffic-gen-in-vm] Add traffic gen VMI

---

pkg/internal/checkup/checkup.go
pkg/internal/checkup/checkup_test.go
pkg/internal/checkup/executor/executor.go

In order to operate the TRex application, via the traffic gen's serial console, login to the guest OS.

[traffic-gen-in-vm] Executor: Add login to traffic gen VMI

---

pkg/internal/checkup/executor/executor.go
pkg/internal/checkup/executor/testpmd-console.go
pkg/internal/checkup/executor/testpmd/console.go

This PR is moving the testpmd functions to a separate package.

[traffic-gen-in-vm] Move testpmd package

---

pkg/internal/checkup/checkup.go
pkg/internal/checkup/vmi.go
pkg/internal/checkup/vmi/spec.go
pkg/internal/checkup/vmi_test.go

In order to get the Trex configuration, the ConfigMap object generated by the checkup, should be attached to the traffic-gen VMI, and mounted inside the guest [1].
1. Create a volume in the traffic gen VMI, referring to the to the traffic-gen's ConfigMap.
2. Create a disk that refers to the above volume.
3. Using cloud init, mount the above disk to the guest's file system.
The generated ConfigMap is currently empty, until a follow-up PR will fill it up.
~~Based on PR #147, please review only the last three commits.~~
[1] http://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#configmap

[traffic-gen-in-vm] Attach traffic-gen's ConfigMap to traffic gen VMI

---

pkg/internal/checkup/executor/executor.go
pkg/internal/checkup/executor/testpmd/console.go

Now that both traffic generator and the "VMI under test" are VMIs, some params are left ambiguous. 
Refactoring params to avoid future confusion.

[traffic-gen-in-vm] Refactor executer params

---

pkg/internal/checkup/vmi.go

Following PR #149, the traffic-gen ConfigMap contains the TRex configuration file and several Python scripts.
When mounting the disk containing the ConfigMap, the files are read only.
1. Copy the TRex config file to `/etc` in the traffic-gen guest.
2. Create a directory to hold the Python scripts `/opt/tests`.
3. Copy the Python scripts to the above directory.
AFAIU, there is no need to make the Python scripts executable, because they are not executed as standalone scripts,
and do not have a Shebang [1].
[1] https://en.wikipedia.org/wiki/Shebang_(Unix)

[traffic-gen-in-vm] Place TRex config file and scripts

---

pkg/internal/checkup/trex/configfiles.go
pkg/internal/checkup/trex/configfiles_test.go

Currently, the MAC addresses that are embedded in the output string of `GenerateStreamPyFile()` and `GenerateStreamAddrPyFile()` and are not quoted, thus making the Python interpreter fail.
Surround the MAC addresses in quotes.

[traffic-gen-in-vm] Trex, Python scripts: Quote MAC addresses

---

pkg/internal/checkup/checkup.go
pkg/internal/checkup/trex/configfiles.go
pkg/internal/checkup/trex/configfiles_test.go
pkg/internal/checkup/vmi.go

The `t-rex-64` application uses the console for input/output.
We wish to use the console to operate TRex as a client, so we need the traffic-gen's serial console to be free.
Add a systemd unit file so executor could start TRex daemon using the following command:
```bash
systemctl start trex
```
A follow-up PR will actually start TRex from the executor.

[traffic-gen-in-vm] Enable TRex execution using systemd

---

pkg/internal/checkup/executor/executor.go
pkg/internal/checkup/trex/client.go
pkg/internal/checkup/trex/server.go

This PR starts the systemd Unit in charge of running the trex-server application.
It then waits until the server is ready, by polling it from the client side.

[traffic-gen-in-vm] Start trex server service and wait until ready

---

pkg/internal/checkup/vmi.go

Currently, all the boot commands have a `sudo` prefix. This was done because we followed an example in the KubeVirt user guide [1].
Apparently, this is not needed, and considerably slows down the boot process of the traffic-gen VMI.
[1] http://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#as-a-disk

[traffic-gen-in-vm] traffic-gen, boot commands: Remove sudo

---

pkg/internal/checkup/executor/executor.go
pkg/internal/checkup/trex/client.go
pkg/internal/checkup/trex/types.go
pkg/internal/checkup/vmi.go

This PR is adding the command that will initiate the DPDK traffic towards the VMI under test, and in the meanwhile will poll the traffic for drop rates on the traffic-generator side.

[traffic-gen-in-vm] Run traffic towards the VMI under test

---

pkg/internal/checkup/executor/executor.go
pkg/internal/checkup/trex/client.go

This PR is retrieving the traffic gen port stats after the test has run, effectively making the checkup operational again.

[traffic-gen-in-vm] Retrieve port stats from Traffic gen

---

pkg/internal/checkup/executor/executor.go
pkg/internal/checkup/executor/testpmd/console.go

Currently, the exported methods of `testpmd.Console` are receiving a vmiName parameter.
Because this object is supposed to work against a single VMI, a better approach would be to pass the vmiName parameter during the object's construction.
Add a vmiName field to `testpmd.Console`.
Remove the vmiName parameter from all its exported methods.

[traffic-gen-in-vm] testpmd, console: Add vmiName field

---

README.md

Now that the traffic-gen is run by a VMI, This PR is removing traces of it in the README.

README: Remove references of traffic-gen pod

---

.github/workflows/main.yaml
.github/workflows/publish.yaml
.github/workflows/traffic_gen_containerdisk.yaml
.github/workflows/traffic_gen_containerdisk_publish.yaml
.github/workflows/vm_containerdisk.yaml
.github/workflows/vm_containerdisk_publish.yaml

Following PR #163, the `traffic-gen-in-vm` branch was merged to `main`.
Remove it from the CI.

GitHub Actions: Remove traffic-gen-in-vm branch

---

tests/checkup_test.go

Since the current CI develipment is a single node cluster (SNO), the traffic that can pass the checkup without maximazing the PF limit is 8 million packats per seconds.

e2e: Change test trafficGeneratorPacketsPerSecond param

---

pkg/internal/config/config.go
pkg/internal/config/config_test.go

In order to change the user-facing API in a follow-up PR, align the config fields' place with their place in the README.
It helps to differentiate between:
1. Traffic gen related fields.
2. VMI under test related fields.
3. Shared fields.

Refactor config

---

README.md
pkg/internal/checkup/checkup.go
pkg/internal/checkup/executor/executor.go
pkg/internal/reporter/reporter.go
pkg/internal/reporter/reporter_test.go
pkg/internal/status/status.go
tests/checkup_test.go

Following PR #168, the input fields' names were improved.
Align the user-facing output fields to follow the prefixes defined in PR #168.
`trafficGeneratorTxPackets` -> `trafficGenSentPackets`
`trafficGeneratorOutputErrorPackets` -> `trafficGenOutputErrorPackets`
`trafficGeneratorInErrorPackets` -> `trafficGenInputErrorPackets`
`trafficGeneratorNode` -> `trafficGenActualNodeName`
`DPDKVMNode` -> `vmUnderTestActualNodeName`
`DPDKRxTestPackets` -> `vmUnderTestReceivedPackets`
`DPDKRxPacketDrops` -> `vmUnderTestRxDroppedPackets`
`DPDKTxPacketDrops` -> `vmUnderTestTxDroppedPackets`
Align the the internal field names as well.
~~This PR depends on PR #168, please review only the last eight commits.~~

Reporter: Align output field names

---

vms/image-builder/Dockerfile

Currently, we are building VM images using CentOS Stream 8 base image.
CentOS Stream 9 is the latest major version of CentOS Stream. Bump the base image to CentOS Stream 9.
The `libguestfs-tools` package (which contains virt-builder) had been renamed to `guestfs-tools`.
It is important to note that the VM under test and the traffic gen VM will still run on CentOS Stream **8**.

vm image builder: Upgrade to CentOS Stream 9

---

README.md
pkg/internal/config/config.go

In our tests so far, with the current CI hardware, we haven't been able to pass the eight million pps threshold with zero packet loss.
Set the default value of `trafficGenPacketsPerSecond` to eight million.

Config: Reduce default trafficGenPacketsPerSecond

---

pkg/internal/checkup/checkup.go
pkg/internal/checkup/executor/executor.go

As the VM under test changed it name from DPDK VM, to "VM Under Test", this was not changed in all the logs as well.
Replacing name accordingly.

checkup, executor: Remove DPDK VM phrasing from logs

---

tests/checkup_test.go

Currently, `TRAFFIC_GEN_CONTAINER_DISK_IMAGE` and `VM_UNDER_TEST_CONTAINER_DISK_IMAGE` environment
variables are optional.
In case the user does not define them, empty strings are passed to the checkup via the user-supplied ConfigMap.
Pass the container disk URLs only in case they are not empty.
~~This PR depends on PR #180, please review only the last commit.~~

E2E: Conditionally configure containerDisk images

---

tests/checkup_test.go

Currently if one changes the timeout, the change is not expressed on the job wait, and that would cause the job to fail on timeout anyways. Changing the job timeout to depend on the actual checkup timeout.

tests/e2e: Change job timeout to be dynamic

---

pkg/internal/checkup/checkup.go
pkg/internal/checkup/checkup_test.go

This PR adds needed Unit tests for the Run function logic.
Then it add another checkup Run success condition, that makes it so that If no packets were sent from the traffic generator from any reason - the checkup should fail.

checkup: Fail on zero case scenario

---

pkg/internal/checkup/executor/console/console.go
pkg/internal/checkup/executor/console/login.go
pkg/internal/checkup/executor/executor.go
pkg/internal/checkup/executor/testpmd/console.go
pkg/internal/checkup/trex/client.go

This PR is refactoring the console package, in order to be consumed as an object, to be used by other packages like the executor, testpmd and trex packages.

console: Refactor package

---

pkg/internal/reporter/reporter_test.go

The current reporter unit tests are testing against a zero results value. 
As the checkup now does not support zero results as a success case, this unit test requires a change.
Refactor unit tests to make them more readable. 
Add non zero success case and  non zero-fail case.

reporter: Refactor Unit tests

---

pkg/internal/checkup/checkup.go
pkg/internal/checkup/checkup_test.go

Currently, the teardown logic is as follows:
1. Remove the VMI under test
2. Remove the traffic gen
3. Remove the traffic gen ConfigMap
4. Wait for VMI under test to be removed
5. Wait for the traffic gen to be removed.
In case any of the above steps fails, the entire teardown fails.
Align this logic with the VM latency checkup, in which the errors are accumulated.

checkup: Fix teardown logic

---

Makefile

Currently, `CRI_BUILD_BASE_IMAGE_TAG` is used to set the tag of the checkup's base image [1].
Rename this variable to `CHECKUP_BASE_IMAGE_TAG` in order to better represent its purpose.
Currently, the value of `CHECKUP_BASE_IMAGE_TAG` is `latest`, which makes the build unpredictable - software versions
might change between builds.
This problem is even worse when building an old version of the checkup.
Set the value of `CHECKUP_BASE_IMAGE_TAG` to the latest ubi9-minimal tag [2].
[1] registry.access.redhat.com/ubi9/ubi-minimal
[2] https://catalog.redhat.com/software/containers/ubi9/ubi-minimal/615bd9b4075b022acc111bf5?push_date=1690889472000&architecture=amd64

Makefile: Set the tag of the checukp's base image

---

pkg/internal/checkup/vmi/spec.go

Add the isolateEmulatorThread option[1] for the two VMIs. This will cause the emulator to run on a CPU of its own, instead of running on the same physical CPUs as the VMs' vCPUs.
In theory, this should help reduce the packet losses.
Currently, there is a bug[2] in KubeVirt that prevents the creation of VMs with an even CPU count and the isolateEmulatorThread option enabled, on nodes with hyperthreading[3] enabled.
The above bug causes the checkup setup phase to fail.
A workaround is to run the checkup on nodes with hyperthreading disabled.
[1] https://kubevirt.io/user-guide/virtual_machines/dedicated_cpu_resources/#requesting-dedicated-cpu-for-qemu-emulator
[2] https://bugzilla.redhat.com/show_bug.cgi?id=2228103
[3] https://en.wikipedia.org/wiki/Hyper-threading

vmi spec: Add isolateEmulatorThread option

---

docs/Configuring_openshift_virtualization_vm_for_dpdk.md

The "Configuring_openshift_virtualization_vm_for_dpdk" document is relevant to OCP 4.13. At the time the OCP documentation was only updated to 4.12.
Now that OCP 4.13 is puiblished - updating the links accordingly.
All links where checked manually to be valid

docs: Update OCP related links

---

docs/Configuring_openshift_virtualization_vm_for_dpdk.md
vms/traffic-gen/scripts/customize-vm
vms/vm-under-test/scripts/customize-vm

This PR is removing the `isolcpus` kernel argument from the VMs image and also from the documentation, as it is no longer needed on RHEL 8,9 [0].
[0] https://access.redhat.com/articles/6126451

Remove isolcpus karg

---

pkg/internal/checkup/trex/configfiles.go
pkg/internal/checkup/trex/configfiles_test.go

When configuring the cores that will run the traffic one needs to think of the current topology.
Currently the traffic-gen-vmi guest is using 8 CPUs: 0-7. Hence the SMT siblings are set by kubevirt to be 0-1,2-3,4-5,6-7. 0-1 are set to be reserved to the OS on the grub linuxcmd [0]. 2-3 should run the trex master and latency threads (running non DPDK processes)
thus - 4,5,6,7 should be assigned to the forwarding CPUs (four in total).
This commit is changing these parameters in the trex server cmdline[1]:
* -c: the number is not changed but now represents the number of hw threads to use per interface pair (including master and latency which are used internally it is still six)
It is changing the trex_cfg.yaml file:
* update CPU mapping to use the appropriate vCPUs
[0] …

trex: Refactor App configuration

---

pkg/internal/checkup/checkup.go

The checkup sometimes fails on setup timeout, although nothing seems to be wrong.
Increasing the timeout to 15m.

checkup: Increase Setup timeout

---

tests/checkup_test.go

It takes the checkup ~ten minutes to reach the Run phase on the dev cluster, so it makes no sense that the e2e timeout is ten minutes. Increasing to one hour.

test/e2e: Increase test timeout

---

Makefile

Bump the checkup's base image to
`registry.access.redhat.com/ubi9/ubi-minimal:9.3-1475`.

Makefile: Bump checkup's base image

---

tests/checkup_test.go

In PR #169, the names of the output fields were changed.
Align the error messages in case the assertions fail.

E2E: Align output error messages

---

docs/Configuring_openshift_virtualization_vm_for_dpdk.md

This PR updates the DPDK manual with the needed adjustments in order to avoid SMT Alignment errors on nodes where SMT in enabled.
For more information see Jira [CNV-31584](https://issues.redhat.com/browse/CNV-31584)

Docs: Add full-pcpu-only support

---

pkg/internal/checkup/executor/console/console.go
pkg/internal/checkup/executor/executor.go
pkg/internal/checkup/executor/testpmd/console.go
pkg/internal/checkup/trex/client.go

This PR is refactoring the logs that are used on the trex and testpmd clients. 
These logs are logging the input/output of the serial console.
In order to make the DPDK-checkup job logs more readable:
- Removing duplicates logs
- Adding more information when needed

Executer/console: Refactor logs

---

pkg/internal/checkup/trex/client.go
pkg/internal/checkup/trex/client_test.go

The trex/client is a wrapper for the trex-console binary on the guest.
This PR adds the needed checks to make sure that the checkup fails in case the trex-console command failed.
It also logs the error on the logs so that users can understand what went wrong.
~~This PR depends on https://github.com/kiagnose/kubevirt-dpdk-checkup/pull/207.
only 2 last commits are relevant.~~

trex/client: Add check for trex-console failures

---

vms/traffic-gen/scripts/customize-vm
vms/vm-under-test/scripts/customize-vm

Currently, the mounting of hugepages is performed by the `/usr/bin/dpdk-checkup-boot.sh` script which is executed on every boot.
Move it to the VM configuration phase, so it would be done automatically by the operating system.

vm-customize: Automatically mount hugepages

---

pkg/internal/checkup/checkup.go
pkg/internal/checkup/checkup_test.go
pkg/internal/checkup/vmi.go

This PR introduces a new configmap to the checkup, that will be consumed by the VMI-under-test VMI.
In future PRs this configmap will be used to insert scripts to the guest.

checkup: Introduce vmi under test configmap

---

pkg/internal/checkup/vmi.go

Currently, `driverctl` is executed on every boot.
There is no need to run it before we configure `tuned-adm profile` and reboot the VM.

VM boot script: Run driverctl from second boot

---

vms/traffic-gen/scripts/customize-vm

The traffic-gen's `customize-vm` script is the same as the one used by the VM-under-test, with an
additional step of TRex installation.
Reorder the file so the two scripts would be aligned.

Traffic-gen, customize-vm: Align with VM-under-test

---

pkg/internal/checkup/executor/console/console.go
pkg/internal/checkup/executor/console/login.go
pkg/internal/checkup/executor/executor.go
pkg/internal/checkup/vmi.go
pkg/internal/checkup/vmi_test.go
pkg/internal/config/config.go

Currently, the checkup creates a `cloud-user` user using cloud-init, and logs in to the VMs using its credentials.
Immediately after logging in, the checkup issues the `sudo su` command, thus effectively running as the root user.
Logging in as root simplifies the login operation, and remove problems that can occur when certain assumptions are made when performing the `sudo su` step - for example:
1. Not expecting the sudo warning message
2. Not expecting to enter the user's password again.
Also remove the creation of `cloud-user` from cloud-init, since it is no longer needed.

Log in as root

---

pkg/internal/checkup/checkup.go
pkg/internal/checkup/checkup_test.go
pkg/internal/checkup/vmi.go
pkg/internal/checkup/vmi/spec.go
pkg/internal/config/config.go
vms/traffic-gen/scripts/customize-vm
vms/vm-under-test/scripts/customize-vm

This PR introduces a new algorithm to make sure that the checkups start only after the vmi properly configured for DPDK.
Instead of waiting for the VMI guest-agent condition to be true, introducing a guest-agent-ping probe that will poll for the marker file signaling that the VMI is ready.
~~It relies on #220, first 4 commits do not belong to this PR~~

checkup: Add guest agent ping wait

---

Makefile

Currently only the actual checkup image is pushed to quay on every PR merged.
This PR does so also to the vm-under-test and traffic-gen container-disk images.

Add commit based tags on pushed quay images

---

README.md
pkg/internal/config/config.go
pkg/internal/config/config_test.go

Currently, trafficGenContainerDiskImage defaults to:
`quay.io/kiagnose/kubevirt-dpdk-checkup-traffic-gen:main`.
and vmUnderTestContainerDiskImage defaults to:
`quay.io/kiagnose/kubevirt-dpdk-checkup-vm:main`.
This may lead to unexpected behavior when using an older checkup version in combination with the latest container disk images (tagged as `main`).
Make the fields mandatory in order for the user to specify them explicitly.

Make container disk images mandatory

---

pkg/internal/checkup/executor/console/login.go
vms/traffic-gen/scripts/build-vm-image
vms/traffic-gen/scripts/customize-vm
vms/vm-under-test/scripts/build-vm-image
vms/vm-under-test/scripts/customize-vm

CentOS stream 8 had reached EOL [1] and it breaks our automation for building the container disk image due to [2].
Our console package does not correctly handle Bracketed-paste [3], disable it for now.
[1] https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/
[2] https://serverfault.com/questions/1161816/mirrorlist-centos-org-no-longer-resolve
[3] https://en.wikipedia.org/wiki/Bracketed-paste

Bump container disk images to CentOS stream 9

---

.golangci.yml
Makefile
go.mod

"1.22" is not a valid toolchain name.
[1] https://go.dev/doc/toolchain#name
[2] https://github.com/golang/go/issues/62278#issuecomment-1693538776

go.mod: Add patch version to the go directive

---

Makefile
hack/go-mod-version.sh

This action seems to be redundant and aggressive.
[1] https://go.dev/ref/mod#go-mod-tidy
[2] https://go.dev/ref/mod

Makefile, vendor: Remove compat flag
